services:
  yp_postgres:
    image: postgres:17
    environment:
      - LANG=C.UTF-8
    container_name: yp_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  yp_project:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: yp_docker
    depends_on:
      - yp_postgres
    volumes:
      - ./:/YP
      - ./staticfiles:/YP/staticfiles
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  postgres_data:
    external: true
